### PR TITLE
Fixes 96

### LINKED ISSUE #96: Pictograms not loading properly when searching
**Describe the bug**
When searching for pictograms, the search query uses a "random" user.

**To Reproduce**
1. Create a guardian in the database
2. On that guardian, upload a private pictogram
3. search for the image. The pictogram won't show up. The pictogram may only show up if it is the first user in the database.

One can also
1. Open file `PictogramController.cs` and go to the method `ReadAllPictograms` just after the `user` variable has been assigned
2. Create a console print that tells the name of the user is being used in the query
3. See that the print does not correspond to  the name of the user that is logged in. It may just as well be a citizen and not a guardian.

**Expected behavior**
When searching for pictograms, any access to the database should consider the user that is actually making the query, instead of a random one.

**Environment (please complete the following information):**
- Tested in a local database, copied from the actual one.

### PR DESCRIPTION
**Pull request by ThomasMG**
fixes #96 
Added a line that specifies a constraint on the user ID.
Does not work on develop right now, because another PR introduced an error, where queries don't work. They are working on fixing it, as well as making tests that cover the methods used for reading pictograms, which includes the one edited in this PR.

### CODE REVIEW

File: GirafRest/Services/GirafService.cs [hunk 1]
```diff
@@ -77,6 +77,7 @@ public async Task<GirafUser> LoadUserWithDepartment(System.Security.Claims.Claim
             var usr = (await _userManager.GetUserAsync(principal));
             if (usr == null) return null;
```
Comment (Simon97) [inline GirafRest/Services/GirafService.cs:78]: Jeg er med på, at det ikke er jer der har lavet den del, men er det ikke underligt at man tjekker for null og så bare returnere null? Så kunne man jo ligeså godt lade være med at tjekke det? :D
